---
output:
html_document:
self_contained: false
lib_dir: "libs"
fig_height: 2
fig_width: 4
params:
element: "forage-fish"
---

```{r, echo=FALSE, message=F, warning=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F)
library(infographiq)
```

<base target="_parent">

```{r}
tryCatch(
    plot_timeseries(
        csv_tv  = "http://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_EI_FBC.csvp?time%2Cspecies_group%2Cmean_cpue%2CSeup%2CSelo&distinct()",
        title   = "Hake Abundance",
        y_label = "mean_cpue (ln(catch+1))",
        skip    = 0,
        filter  = "species_group == \"Hake\"",
        col_t   = "time (UTC)",
        col_y   = "mean_cpue (ln(catch+1))",
        group_by= NULL
    ),
    error = function(e) e
)
```

```{r}
tryCatch(
    plot_timeseries(
        csv_tv  = "http://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_EI_FBC.csvp?time%2Cspecies_group%2Cmean_cpue%2CSeup%2CSelo&distinct()",
        title   = "Sardine Abundance",
        y_label = "mean_cpue (ln(catch+1))",
        skip    = 0,
        filter  = "species_group == \"Hake\"",
        col_t   = "time (UTC)",
        col_y   = "mean_cpue (ln(catch+1))",
        group_by= NULL
    ),
    error = function(e) e
)
```

```{r}
tryCatch(
    plot_timeseries(
        csv_tv  = "http://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_EI_FBC.csvp?time%2Cspecies_group%2Cmean_cpue%2CSeup%2CSelo&distinct()",
        title   = "Anchovy Abundance",
        y_label = "mean_cpue (ln(catch+1))",
        skip    = 0,
        filter  = "species_group == \"Anchovy\"",
        col_t   = "time (UTC)",
        col_y   = "mean_cpue (ln(catch+1))",
        group_by= NULL
    ),
    error = function(e) e
)
```

```{r}
tryCatch(
    plot_timeseries(
        csv_tv  = "http://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_EI_FBC.csvp?time%2Cspecies_group%2Cmean_cpue%2CSeup%2CSelo&distinct()",
        title   = "Sanddab Abundance",
        y_label = "mean_cpue (ln(catch+1))",
        skip    = 0,
        filter  = "species_group == \"Sanddabs\"",
        col_t   = "time (UTC)",
        col_y   = "mean_cpue (ln(catch+1))",
        group_by= NULL
    ),
    error = function(e) e
)
```

```{r}
tryCatch(
    plot_timeseries(
        csv_tv  = "http://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_EI_FBC.csvp?time%2Cspecies_group%2Cmean_cpue%2CSeup%2CSelo&distinct()",
        title   = "Rockfish Juveniles Abundance",
        y_label = "mean_cpue (ln(catch+1))",
        skip    = 0,
        filter  = "species_group == \"Rockfish juveniles\"",
        col_t   = "time (UTC)",
        col_y   = "mean_cpue (ln(catch+1))",
        group_by= NULL
    ),
    error = function(e) e
)
```

```{r}
tryCatch(
    plot_timeseries(
        csv_tv  = "http://oceanview.pfeg.noaa.gov/erddap/tabledap/FED_Rockfish_Catch.csvp?time%2Ccatch%2Cmaturity%2Carea%2Cstrata&latitude%3E=35.5&latitude%3C=38&catch%3E0&common_name=%22PACIFIC%20MACKEREL%22",
        title   = "Pacific Mackerel Abundance",
        y_label = "Catch",
        skip    = 0,
        filter  = NULL,
        col_t   = "time (UTC)",
        col_y   = "catch",
        group_by= NULL
    ),
    error = function(e) e
)
```
