---
output:
html_document:
self_contained: false
lib_dir: "libs"
fig_height: 2
fig_width: 4
params:
element: "jellies"
---

```{r, echo=FALSE, message=F, warning=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F)
library(infographiq)
```

<base target="_parent">

```{r}
tryCatch(
    plot_timeseries(
        csv_tv  = "https://raw.githubusercontent.com/marinebon/info-mb/master/prep/data/forage_inverts/FED_Gelatinous_catch.csv",
        title   = "Gelatinous Catch",
        y_label = "Catch",
        skip    = 0,
        filter  = NULL,
        col_t   = "yr",
        col_y   = "catch",
        group_by= NULL
    ),
    error = function(e) e
)
```
Gelatinous species: Pyrosoma, Salp, Thetys Salp, Heteropd<br>
Jelly species: Fried Egg Jelly, Sea Nettle, Purple-striped Jelly, Moon Jelly.

```{r}
tryCatch(
    plot_timeseries(
        csv_tv  = "https://raw.githubusercontent.com/marinebon/info-mb/master/prep/data/forage_inverts/FED_Jellies_catch..csv",
        title   = "Jellies Catch",
        y_label = "Catch",
        skip    = 0,
        filter  = NULL,
        col_t   = "yr",
        col_y   = "catch",
        group_by= NULL
    ),
    error = function(e) e
)
```
The Fisheries Ecology Division (FED, https://swfsc.noaa.gov/GroundfishAnalysis/) of the Southwest Fisheries Science Center (SWFSC)  midwater trawl survey off central California. Fisheries Ecology Division/SWFSC/NOAA
