---
output:
html_document:
self_contained: false
lib_dir: "libs"
fig_height: 2
fig_width: 4
params:
element: "pinnipeds"
---

```{r, echo=FALSE, message=F, warning=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F)
library(infographiq)
```

<base target="_parent">

```{r}
tryCatch(
    plot_timeseries(
        csv_tv  = "http://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_MM_pup_count.csvp?time,mean_growth_rate",
        title   = "Female sea lion pup growth rate",
        y_label = "Mean growth rate",
        skip    = 0,
        filter  = NULL,
        col_t   = "time (UTC)",
        col_y   = "mean_growth_rate (kg/day)",
        group_by= NULL
    ),
    error = function(e) e
)
```

```{r}
tryCatch(
    plot_timeseries(
        csv_tv  = "http://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_MM_pup_count.csvp?time,mean_weight",
        title   = "Female sea lion pup weight index",
        y_label = "Mean pup weight",
        skip    = 0,
        filter  = NULL,
        col_t   = "time (UTC)",
        col_y   = "mean_weight (kg)",
        group_by= NULL
    ),
    error = function(e) e
)
```

```{r}
tryCatch(
    plot_timeseries(
        csv_tv  = "http://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_MM_pup_count.csvp?time,live_pup_count",
        title   = "Sea lion pup count, San Miguel Isl.",
        y_label = "Average live pup count",
        skip    = 0,
        filter  = NULL,
        col_t   = "time (UTC)",
        col_y   = "live_pup_count (count)",
        group_by= NULL
    ),
    error = function(e) e
)
```
