---
output:
html_document:
self_contained: false
lib_dir: "libs"
fig_height: 2
fig_width: 4
params:
element: "seascape"
---

```{r, echo=FALSE, message=F, warning=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F)
library(infographiq)
```

<base target="_parent">
Seascapes are created with satellite data to find areas of the ocean surface with similar characteristics. Usually cool, productive water (dark red) is prevalent but in 2014-15 conditions were more variable with reduced area of cool productive waters (dark red), and abundance of nutrient deplete nearshore (orange) and influx of offshore (cyan) waters. 

```{r}
tryCatch(
    plot_timeseries(
        csv_tv  = "NA",
        title   = "NA",
        y_label = "NA",
        skip    = 0,
        filter  = NULL,
        col_t   = NULL,
        col_y   = NULL,
        group_by= NULL
    ),
    error = function(e) e
)
```

```{r}
tryCatch(
    plot_timeseries(
        csv_tv  = "",
        title   = "",
        y_label = "",
        skip    = ,
        filter  = ,
        col_t   = ,
        col_y   = ,
        group_by= 
    ),
    error = function(e) e
)
```
